# Generated by Django 5.2.11 on 2026-03-02 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
