# Generated by Django 5.2.11 on 2026-03-15 07:34

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension

class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_post_tags"),
    ]

    operations = [
        TrigramExtension(),
    ]
